/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package data;

import Server.ServerExec;
import java.awt.Color;
import java.util.ArrayList;
import static javafx.application.Platform.exit;
import javax.swing.JLabel;

/**
 *
 * @author juanma
 */
public class FramePuntuacion extends javax.swing.JFrame {

    /**
     * Creates new form FramePuntuacion
     */
    private GameObservable gameObservable;
    ArrayList<JLabel> label = new ArrayList<JLabel>();
    private static JLabel jLabel;

    public FramePuntuacion(GameObservable gameObservable) {
        initComponents();
        this.gameObservable = gameObservable;
        this.setLocation(650, 0);

        for (int i = 0; i < ServerExec.jugadores.size(); i++) {
            jLabel = new JLabel("Jlabel" + i);
            jLabel.setText(ServerExec.jugadores.get(i).getName());
            jLabel.setBounds(0, 0, 200, 200);
            jLabel.setBackground(Color.green);
            jLabel.setOpaque(true);
            label.add(jLabel);
        }
        for (JLabel j : label) {
            this.jPanelChulo.add(j);
        }
        this.add(jPanelChulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelChulo = new javax.swing.JPanel();
        jButtonCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelChuloLayout = new javax.swing.GroupLayout(jPanelChulo);
        jPanelChulo.setLayout(jPanelChuloLayout);
        jPanelChuloLayout.setHorizontalGroup(
            jPanelChuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChuloLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jButtonCerrar)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanelChuloLayout.setVerticalGroup(
            jPanelChuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChuloLayout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(jButtonCerrar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelChulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelChulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JPanel jPanelChulo;
    // End of variables declaration//GEN-END:variables
}
